### For some reason, this is working. So, for now, let's not call this and simple call the command via a bash script command. 


---
- name: deploy k8
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    #hosts_file: /root/hosts
    #config_file: /root/config-default.sh
    #working_dir: /root
  tasks:
  
        
      - name: display path
        debug:
          msg: "{{ working_dir }}/{{ server_group }}/kubernetes/cluster/"
            
      - name: deploy k8
        shell: (cd {{ working_dir }}/{{ server_group }}/kubernetes/cluster/ && KUBERNETES_PROVIDER=ubuntu ./kube-up.sh)
        async: 600
        poll: 5
        register: deploy_output
        
      - name: debug
        debug:
          msg: deploy_output
          