
---
- name: Load servers from hosts file
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    #working_dir: /root
    hosts_file: "{{ working_dir }}/{{ server_group }}-hosts"
    config_file: "{{ working_dir }}/{{ server_group }}/kubernetes/cluster/ubuntu/config-default.sh"
        
  tasks:
    - name: retrieve the list of servers 
      command: cat {{ hosts_file }}
      register: servers_to_install_k8
      
    - name: Add New Servers to an in-memory Group
      add_host:
        name={{ item }}
        ansible_ssh_host={{ item }}
        ansible_ssh_user=root
        groupname=SERVERS_GRP
      with_items: servers_to_install_k8.stdout_lines


- name: run the reconf docker script on each host and add NAT rule to fix outbound internet access for containers
  hosts: SERVERS_GRP
  gather_facts: False
  vars:
    #working_dir: /root
    hosts_file: "{{ working_dir }}/{{ server_group }}-hosts"
    config_file: "{{ working_dir }}/{{ server_group }}/kubernetes/cluster/ubuntu/config-default.sh"
        
  tasks:

      - name: reconf docker
        command: /root/kube/reconfDocker.sh
      - name: more iptables1     
        command: iptables -t nat -N KUBE-OUTBOUND-NAT
      - name: more iptables2
        command: iptables -t nat -A KUBE-OUTBOUND-NAT -d 172.16.0.0/16 -o eth0 -j RETURN
      - name: more iptables 3       
        command: iptables -t nat -A KUBE-OUTBOUND-NAT -j MASQUERADE
      - name: more iptables4       
        command: iptables -t nat -A POSTROUTING -j KUBE-OUTBOUND-NAT
      - name: more iptables5       
        command: iptables-save 

