 
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
    deployment: v1

spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
    deployment: v1
   
---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-rc
spec:
  replicas: 2
  
  selector:
    app: nginx
    deployment: v1
    
  template:
    metadata:
      labels:
        app: nginx
        deployment: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        
   
   
   