
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-with-content-rc
spec:
  replicas: 2
  
  selector:
    app: website
    deployment: v2
    
  template:
    metadata:
      labels:
        app: website
        deployment: v2
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-with-content
        ports:
        - containerPort: 80
        
   
   